[package]
name = "plus_forecast"
version = "0.0.1"
authors = []
description = """TBD"""
keywords = []
license = "MIT"

[dependencies]
serde = "^1.0.11"
chrono = "0.4.0"
approx = "0.1.1"
ndarray = "0.10.6"
num = "0.1.40"
clippy = {version = "^0.0.150", optional = true}
